### ISSUE TITLE
Compose Activity broken when starting a session

### ISSUE THREAD

**Issue by mattcreaser** [goinstant/android-sdk-guides#11]
Compose activity was updated to use a different menu, which breaks logic in its parent class SubActivity.
1. Go to the compose activity.
2. Attempt to start a session.

App crashes.
1. Start a session.
2. Go to the compose activity.

SOS button is not hidden.

**Comment by raJSN** [comment]
I m also facing this issue. app is crashing as soon as we lauch it and agent get one ring.
