### ISSUE TITLE
Dependency not resolved

### ISSUE THREAD

**Issue by madhankumardroid** [goinstant/android-sdk-guides#37]
Failed to resolve: com.salesforce.service:sos:2.1.2

**Comment by evanisnor** [comment]
Hey @madhankumardroid, sorry but we don't maintain this repo anymore. Check out our latest examples [here](https://github.com/forcedotcom/ServiceSDK-Android/tree/master/Examples) and our developer guides [here](https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_android.meta/service_sdk_android/servicesdk_android_dev_guide.htm). Specifically, check out our [installation guide](https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_android.meta/service_sdk_android/android_install_sdk.htm#ess_sdk_setup_android) for help locating the dependency.

Cheers!
